name: g_a_s_app_rekadigi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  introduction_screen: 3.1.4
  get_storage: 2.1.1
  text_divider: 1.0.0
  flutter_svg: 1.1.6
  google_fonts: 4.0.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/icons/
  uses-material-design: true

fonts: 
  - family: Poppins
    fonts: 
      - asset: fonts/Poppins-Regular.ttf
  - family: DancingScript
    fonts: 
      - asset: fonts/DancingScript-Regular.ttf

