// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtR1rNJbo4UvT7sFd1W7xn_1LFBNbyRE0',
    appId: '1:708436128118:web:7160b6d2c5a52da3524a57',
    messagingSenderId: '708436128118',
    projectId: 'gas-indonesia',
    authDomain: 'gas-indonesia.firebaseapp.com',
    storageBucket: 'gas-indonesia.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAveK311sV6WvvMzREG0etsGSb0hlU8NPE',
    appId: '1:708436128118:android:c2f4527500683445524a57',
    messagingSenderId: '708436128118',
    projectId: 'gas-indonesia',
    storageBucket: 'gas-indonesia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiZtf-cOr3BvpwARoOiS7FUmSSQYjSxAo',
    appId: '1:708436128118:ios:72499f0cacef6749524a57',
    messagingSenderId: '708436128118',
    projectId: 'gas-indonesia',
    storageBucket: 'gas-indonesia.appspot.com',
    iosClientId: '708436128118-ulo0he110j38u7gv67sr99o4766go5qh.apps.googleusercontent.com',
    iosBundleId: 'id.rekadigi.gASAppRekadigi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiZtf-cOr3BvpwARoOiS7FUmSSQYjSxAo',
    appId: '1:708436128118:ios:72499f0cacef6749524a57',
    messagingSenderId: '708436128118',
    projectId: 'gas-indonesia',
    storageBucket: 'gas-indonesia.appspot.com',
    iosClientId: '708436128118-ulo0he110j38u7gv67sr99o4766go5qh.apps.googleusercontent.com',
    iosBundleId: 'id.rekadigi.gASAppRekadigi',
  );
}
