class RandomComment {
  /// komentar / ulasan

  final List<String> esKrim = [
    'Rasanya lezat sekali!',
    'Harganya terjangkau dan rasa vanilla-nya enak.',
    'Anak-anak pasti suka!',
    'Sangat cocok untuk cuaca panas.',
    'Tersedia berbagai rasa lainnya juga!',
    'Es krim paling enak yang pernah saya coba.',
    'Kualitas dan rasa yang luar biasa!',
    'Suka sekali dengan teksturnya yang lembut.',
    'Rekomendasi untuk pecinta es krim!',
    'Tidak terlalu manis, pas untuk lidah saya.',
    'Saya selalu beli es krim ini setiap kali ke pasar.',
    'Kemasan yang menarik membuat saya tertarik mencobanya.',
    'Terus membuat variasi rasa yang unik dan menarik.',
    'Porsi cukup besar dan puas setelah makan.',
    'Penjualnya ramah dan baik pelayanannya.',
    'Kualitas produk selalu konsisten dan baik.',
    'Harga sangat terjangkau untuk kualitas sebagus ini.',
    'Pilihan yang tepat untuk camilan sore.',
    'Es krim terenak di kota ini, tidak bisa berhenti mencobanya!',
    'Es krim ini memiliki tekstur yang begitu lembut dan lezat. Setiap gigitan memberikan sensasi yang luar biasa di lidah. Rasanya begitu autentik dan beragam varian rasanya membuat saya ingin mencoba semuanya.',
    'Sangat sulit untuk menemukan es krim yang sebaik ini. Saya selalu kembali ke sini untuk menikmati rasa yang khas dan tidak bisa saya temukan di tempat lain. Pelayanannya juga sangat baik.',
    'Tidak ada yang bisa mengalahkan rasa es krim ini. Harganya mungkin sedikit lebih tinggi, tetapi sebanding dengan pengalaman yang saya dapatkan. Cocok untuk segala suasana dan saya tidak pernah bosan mencobanya.',
    'Es krim ini adalah jawaban untuk hari-hari panas. Teksturnya yang lembut dan rasa buah asli yang begitu kental membuat saya ketagihan. Setiap rasa memberikan pengalaman yang berbeda.',
    'Saya sudah mencicipi berbagai macam es krim, tetapi yang ini benar-benar istimewa. Kualitas bahan yang digunakan terasa dalam setiap gigitan. Rasanya begitu segar dan tidak terlalu manis.',
    'Rekomendasi terbaik untuk pecinta es krim! Rasanya tidak bisa saya deskripsikan dengan kata-kata. Anda harus mencobanya sendiri untuk mengerti betapa enaknya es krim ini.',
    'Saya selalu menemukan kesulitan untuk berhenti makan es krim ini. Setiap rasa memiliki keunikan dan kelezatan masing-masing. Sudah beberapa kali saya membawa pulang beberapa porsi karena terlalu enak!',
    'Es krim paling lezat yang pernah saya coba. Saya sering datang ke sini bersama teman-teman dan kami selalu menikmati setiap suapan. Varian rasanya sangat beragam dan tidak pernah mengecewakan.',
    'Bukan hanya rasa es krimnya yang luar biasa, tetapi juga presentasinya yang indah. Setiap porsi es krim dihidangkan dengan penuh kreativitas dan membuat saya terkesan. Cocok untuk diunggah ke media sosial!',
    'Saya tidak bisa menemukan kata yang tepat untuk menggambarkan kelezatan es krim ini. Rasanya seperti sebuah petualangan rasa di mulut. Jika Anda mencari es krim yang luar biasa, maka inilah tempatnya.',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ];

  final List<String> batik = [
    'Baju batiknya cantik sekali!',
    'Motif batiknya unik dan menarik perhatian.',
    'Kain batiknya nyaman dipakai.',
    'Sangat cocok untuk acara formal.',
    'Bahan batiknya berkualitas tinggi.',
    'Tidak pernah bosan mengoleksi batik dari sini.',
    'Kombinasi warna batiknya indah.',
    'Batiknya terlihat mewah dan elegan.',
    'Harga batiknya sebanding dengan kualitas.',
    'Batik ini benar-benar mencerminkan budaya Indonesia.',
    'Dapat dipakai dalam berbagai kesempatan.',
    'Batiknya membuat penampilan saya semakin berkelas.',
    'Saya suka dengan sentuhan modern pada desain batik ini.',
    'Baju batiknya sangat pas dengan ukuran saya.',
    'Batik yang dijual di sini memiliki banyak pilihan motif.',
    'Dapat dipadukan dengan aksesori yang beragam.',
    'Cocok untuk dipakai sehari-hari atau acara spesial.',
    'Batik ini benar-benar membuat saya bangga dengan budaya Indonesia.',
    'Baju batiknya tahan lama dan tidak mudah pudar.',
    'Motifnya benar-benar unik dan tidak pasaran.',
    'Baju batik ini memiliki desain yang begitu elegan dan anggun. Motifnya sangat unik dan mencerminkan keindahan budaya Indonesia. Saya sangat senang mengenakannya di acara formal dan mendapat banyak pujian.',
    'Saya tidak bisa cukup mengagumi baju batik ini. Kualitas bahan yang digunakan sangat terasa dan nyaman di kulit. Sudah beberapa kali mencucinya, tetapi warnanya tetap tajam dan motifnya tidak luntur.',
    'Pakaian batik ini sangat tahan lama. Sudah bertahun-tahun saya memiliki baju ini dan masih terlihat baru. Hal ini membuktikan bahwa kualitas dan kerajinan dalam pembuatannya sangat baik.',
    'Baju batik ini benar-benar mencuri perhatian. Saya merasa begitu percaya diri saat memakainya. Warna-warnanya sangat cocok dengan berbagai aksesori dan menjadikan penampilan saya semakin menonjol.',
    'Batik ini benar-benar memiliki aura klasik yang tak tergantikan. Saya merasa terhubung dengan budaya leluhur saat mengenakannya. Pilihan yang tepat untuk acara-acara khusus.',
    'Saya senang bisa mendapatkan baju batik dengan kualitas sebaik ini. Walaupun harganya sedikit lebih tinggi, tetapi hasilnya benar-benar sebanding. Saya merasa puas dan bangga bisa memiliki produk lokal berkualitas.',
    'Motif dan desain batik ini sangat unik dan berbeda dari yang lain. Saya merasa seperti memiliki karya seni yang bisa saya kenakan. Pilihan yang tepat untuk memberi kesan istimewa pada penampilan.',
    'Baju batik ini sangat pas dan nyaman saat dikenakan. Bahan kainnya lembut dan tidak membuat gatal. Saya juga suka dengan cara pembuatannya yang begitu detail dan teliti.',
    'Koleksi batik saya tidak lengkap tanpa baju ini. Saya merasa begitu bangga bisa memiliki batik dengan motif yang begitu istimewa. Saya selalu mendapatkan komentar positif saat memakainya.',
    'Pakaian batik ini tidak hanya sekadar pakaian, tetapi juga menceritakan sebuah cerita budaya. Saya merasa terhubung dengan akar budaya kami dan menjadi bagian dari warisan leluhur.',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ];

  final List<String> kerudung = [
    'Kerudungnya cantik sekali!',
    'Warnanya cocok dengan berbagai outfit.',
    'Tampil lebih anggun dengan kerudung ini.',
    'Kerudungnya adem dan nyaman dipakai.',
    'Dapat dipakai untuk berbagai kesempatan.',
    'Motifnya membuat kerudung ini terlihat lebih menarik.',
    'Kerudungnya mudah diatur dan tidak ribet.',
    'Kualitas bahan kerudungnya sangat bagus.',
    'Warnanya tidak luntur saat dicuci.',
    'Dapat dipakai dalam cuaca panas maupun dingin.',
    'Kerudung ini membuat penampilan semakin syar\'i.',
    'Motifnya selalu up-to-date dengan tren terbaru.',
    'Sangat cocok sebagai hadiah untuk orang tersayang.',
    'Kerudung ini memberi kesan lebih elegan.',
    'Desainnya modern dan sesuai perkembangan zaman.',
    'Kerudungnya praktis dan tidak perlu peniti.',
    'Saya senang dengan variasi warna kerudung yang ada.',
    'Bisa dipakai untuk aktivitas sehari-hari.',
    'Kerudung ini benar-benar nyaman di kepala.',
    'Motifnya mencerminkan kepribadian saya.',
    'Kerudung ini benar-benar mencerminkan gaya saya. Bahan yang digunakan sangat nyaman di kepala dan desainnya begitu modern. Saya suka bagaimana kerudung ini bisa meningkatkan penampilan saya.',
    'Saya selalu mendapatkan pujian ketika mengenakan kerudung ini. Motif dan warnanya selalu sesuai dengan berbagai pakaian. Saya merasa lebih percaya diri dengan kerudung ini di kepala.',
    'Kualitas kerudung ini jauh melebihi harapan saya. Tidak hanya tahan lama, tetapi juga terasa sangat adem ketika dikenakan. Cocok untuk berbagai acara dan suasana.',
    'Desain kerudung ini selalu up-to-date dengan tren terbaru. Saya senang dengan variasi warna dan motif yang ditawarkan. Setiap kali saya mengenakannya, saya merasa semakin anggun.',
    'Kerudung ini adalah pilihan sempurna untuk gaya sehari-hari saya. Bahan yang digunakan tidak mudah rusak dan warnanya tetap cerah meskipun sudah sering dicuci. Saya sudah memiliki beberapa warna.',
    'Sangat jarang saya menemukan kerudung yang sesuai dengan kepribadian saya, tetapi kerudung ini berhasil. Desainnya tidak biasa dan memberikan sentuhan modern pada penampilan saya.',
    'Kerudung ini memiliki tekstur yang lembut dan nyaman di kepala. Tidak ada perasaan gatal atau tidak nyaman bahkan setelah lama dikenakan. Saya senang bisa menemukan produk kerudung sebagus ini.',
    'Setiap motif kerudung memberikan kesan yang berbeda. Cocok untuk berbagai acara, baik formal maupun santai. Saya senang dengan cara kerudung ini dapat mengubah tampilan saya dengan mudah.',
    'Saya sangat menghargai usaha yang diletakkan pada detail kerudung ini. Motifnya tampak begitu terperinci dan memberikan kesan mewah. Kerudung ini adalah salah satu aksesori favorit saya.',
    'Kerudung ini adalah investasi yang baik untuk koleksi pakaian saya. Kualitasnya tidak mengecewakan dan modelnya selalu mengikuti tren terbaru. Saya suka mencoba gaya berbeda dengan kerudung ini.',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ];
  final List<String> buah = [
    'Buahnya segar dan enak dimakan.',
    'Rasanya manis dan juicy!',
    'Kualitas buahnya sangat baik.',
    'Buahnya besar dan berwarna cerah.',
    'Baunya harum dan menggugah selera.',
    'Buahnya cocok untuk camilan sehat.',
    'Dapat dinikmati sebagai cemilan atau tambahan makanan.',
    'Rasa dan tekstur buahnya sempurna.',
    'Kaya akan nutrisi dan serat.',
    'Bisa diolah menjadi berbagai hidangan lezat.',
    'Buah ini membantu menjaga kesehatan kulit.',
    'Dikonsumsi rutin, buah ini dapat meningkatkan daya tahan tubuh.',
    'Buahnya memberikan sensasi kesegaran.',
    'Varietas buahnya beragam dan menarik.',
    'Cocok sebagai tambahan dalam berbagai resep makanan.',
    'Buah ini mengandung banyak vitamin dan mineral.',
    'Dapat dijadikan jus atau smoothie yang lezat.',
    'Buah ini bagus untuk menjaga kesehatan jantung.',
    'Kaya akan antioksidan dan zat-zat bermanfaat lainnya.',
    'Buahnya cocok untuk semua usia.',
    'Buah-buahan yang disediakan sangat segar dan berkualitas tinggi. Setiap kali saya membeli, rasanya seperti mendapatkan potongan buah langsung dari kebun sendiri. Sangat puas dengan kualitasnya!',
    'Kualitas dan rasa buah di sini selalu konsisten. Baunya harum dan menggugah selera. Saya suka betapa tekstur dan rasa buahnya selalu terjaga, membuatnya menjadi pilihan terbaik untuk camilan sehat.',
    'Sangat puas dengan beragam jenis buah yang ditawarkan. Dari buah-buahan eksotis hingga yang lebih umum, semuanya memiliki kualitas yang baik. Buah-buahannya selalu matang dengan sempurna.',
    'Buah-buahan yang disediakan mengandung banyak nutrisi penting. Saya merasa lebih sehat setelah rajin mengonsumsinya. Cocok untuk dijadikan tambahan dalam menu harian.',
    'Saya sering memesan berbagai jenis buah dari sini dan hasilnya selalu memuaskan. Buahnya besar, manis, dan rasanya sangat segar. Bisa dijadikan pilihan sempurna untuk menciptakan hidangan sehat.',
    'Buah-buahan di sini sangat cocok untuk keluarga saya. Anak-anak suka dengan rasa manis dan juicy-nya, sementara saya senang dengan nutrisi yang diberikan oleh buah-buahan ini. Sangat praktis untuk mengisi lemari buah kami.',
    'Dari segi penampilan dan rasa, buah-buahan di sini tidak pernah mengecewakan. Buah-buahannya selalu terlihat menarik dan terjaga kesegarannya. Saya merasa senang bisa memiliki akses ke buah-buahan berkualitas tinggi.',
    'Buah-buahan ini bisa dinikmati sebagai camilan sehat atau diolah menjadi hidangan lezat. Kualitas buah-buahannya sangat baik dan cocok untuk berbagai resep masakan. Saya merasa terinspirasi untuk menciptakan menu baru dengan buah-buahan ini.',
    'Dengan mengonsumsi berbagai jenis buah di sini, saya merasa lebih bertenaga dan sehat. Buah-buahan ini memberikan sensasi kesegaran dan memberi dampak positif pada kesehatan saya secara keseluruhan.',
    'Saya sangat merekomendasikan berbagai buah di sini kepada semua orang yang peduli dengan kesehatan dan nutrisi. Dari segi rasa, kualitas, dan manfaat kesehatan, buah-buahan di sini adalah pilihan yang tepat.',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ];
  final List<String> dri = [
    'Pelayanannya sangat profesional dan membantu kami mengatasi masalah teknologi.',
    'Konsultan teknologi ini memberikan solusi yang inovatif dan efektif.',
    'Sangat puas dengan hasil kerja dari jasa konsultan ini.',
    'Tim konsultan memiliki pengetahuan yang mendalam tentang teknologi terkini.',
    'Pekerjaan diselesaikan dengan cepat dan akurat.',
    'Konsultan ini sangat responsif dan siap membantu kapan saja.',
    'Pandangan mereka tentang strategi teknologi sangat berharga.',
    'Kami merasa lebih percaya diri dalam menghadapi tantangan teknologi berkat bantuan konsultan ini.',
    'Kualitas layanan dan saran yang diberikan luar biasa.',
    'Dengan bantuan konsultan ini, kami berhasil mengoptimalkan sistem teknologi kami.',
    'Mereka membantu kami mengidentifikasi dan mengatasi masalah yang sulit dipecahkan sebelumnya.',
    'Konsultan ini membantu kami menghemat waktu dan sumber daya.',
    'Hasil kerjanya sesuai dengan harapan dan bahkan melebihi ekspektasi kami.',
    'Konsultan ini memiliki pendekatan yang terstruktur dan sistematis dalam mengatasi masalah.',
    'Pengalaman dan kompetensi tim konsultan sangat mengesankan.',
    'Kami merasa lebih siap menghadapi transformasi digital berkat konsultan ini.',
    'Konsultan ini membantu kami merancang strategi teknologi yang cocok dengan visi bisnis kami.',
    'Pelayanannya tidak hanya sekadar memberikan solusi, tetapi juga memberikan pemahaman yang mendalam.',
    'Konsultan ini sangat adaptif terhadap perubahan kebutuhan kami.',
    'Hasilnya terukur dan memberikan dampak positif pada efisiensi operasional kami.',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ];
  final List<String> travel = [
    'Pengalaman perjalanan luar negeri yang tak terlupakan, semuanya diatur dengan baik.',
    'Timnya sangat profesional dan membantu kami menjelajahi tempat-tempat menakjubkan.',
    'Pelayanan yang ramah dan detail dalam setiap rincian perjalanan membuat semuanya lebih mudah.',
    'Dengan bantuan jasa travel ini, kami berhasil mengunjungi tempat-tempat impian kami.',
    'Semua aspek perjalanan kami diatur dengan rapi, dari tiket pesawat hingga akomodasi.',
    'Sangat puas dengan paket perjalanan yang ditawarkan, semuanya sesuai dengan ekspektasi.',
    'Kami dapat menikmati berbagai pengalaman budaya dan kuliner yang mengesankan.',
    'Pemandu wisata yang berpengetahuan luas membuat kami lebih menghargai destinasi yang kami kunjungi.',
    'Setiap momen perjalanan dirawat dengan baik dan hasilnya adalah kenangan indah.',
    'Kami berhasil menjelajahi tempat-tempat tersembunyi dan mengalami petualangan yang luar biasa.',
    'Jasa travel ini membantu kami merencanakan liburan yang sempurna tanpa harus khawatir tentang detailnya.',
    'Dengan jasa travel ini, kami merasa lebih tenang dan dapat benar-benar menikmati perjalanan kami.',
    'Destinasi yang dipilih sangat menarik dan beragam, membuat perjalanan kami penuh warna.',
    'Paket perjalanan yang disusun dengan cermat menghadirkan pengalaman yang unik dan berkesan.',
    'Mereka mengurus semua logistik perjalanan sehingga kami dapat fokus menikmati setiap momen.',
    'Timnya sangat responsif terhadap pertanyaan dan permintaan kami, menjadikan perjalanan kami lancar.',
    'Setiap tempat yang kami kunjungi memberikan cerita dan kenangan yang tak terlupakan.',
    'Kami merasa diurus dengan baik dan didukung sepanjang perjalanan kami.',
    'Kami merasa lebih bijaksana setelah menjelajahi tempat-tempat budaya dan sejarah yang menarik.',
    'Dengan bantuan jasa travel ini, kami mendapatkan panduan lokal yang membantu kami mengenal lebih dalam tempat yang kami kunjungi.',
    'Hasil perjalanan wisata luar negeri kami lebih dari yang kami harapkan, semuanya fantastis!',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ];
  final List<String> fotografi = [
    'Hasil fotografi yang luar biasa, mengabadikan momen-momen istimewa dengan indah.',
    'Fotografernya sangat profesional dan membuat kami merasa nyaman di depan kamera.',
    'Sangat puas dengan hasil foto prewedding kami, semuanya terlihat begitu natural.',
    'Kreativitas dalam setiap foto sangat terlihat, membuat hasil fotonya berbeda dan menarik.',
    'Mereka mampu menangkap emosi dan ekspresi dengan sempurna dalam setiap foto.',
    'Kualitas foto dan editingnya sangat mengesankan, semuanya terlihat begitu sempurna.',
    'Saya sangat senang dengan hasil foto produk yang diambil oleh fotografer ini.',
    'Hasil fotonya sesuai dengan ekspektasi dan bahkan melebihi harapan kami.',
    'Fotografernya sangat detail dan teliti, menghasilkan foto yang tajam dan jelas.',
    'Pelayanannya ramah dan sangat profesional, membuat pengalaman foto menjadi menyenangkan.',
    'Dengan hasil foto dari jasa fotografi ini, kami berhasil meningkatkan penjualan produk kami.',
    'Fotografernya memiliki keahlian yang luar biasa dalam mengatur pencahayaan.',
    'Mereka memiliki visi artistik yang kreatif dan menghasilkan foto yang memesona.',
    'Proses pemotretan berjalan dengan lancar dan hasil fotonya luar biasa.',
    'Hasil jepretan fotografer ini mampu menghadirkan kisah dan cerita di balik setiap foto.',
    'Kami sangat puas dengan hasil foto pernikahan kami, semuanya terlihat begitu indah.',
    'Fotografernya sangat sabar dan kooperatif, mengarahkan kami dengan baik selama sesi pemotretan.',
    'Setiap momen penting berhasil ditangkap dengan sempurna, membuat foto kami menjadi berarti.',
    'Kualitas foto yang tinggi dan editing yang elegan membuat hasil fotonya istimewa.',
    'Saya merekomendasikan jasa fotografi ini kepada semua orang yang ingin memiliki kenangan indah.',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ];
  final List<String> pakaian = [
    'Pakaian ini sangat nyaman dipakai sehari-hari.',
    'Desainnya sangat trendi dan cocok untuk segala kesempatan.',
    'Kualitas bahan pakaian sangat baik dan tahan lama.',
    'Saya suka betapa pakaian ini dapat di mix and match dengan berbagai aksesoris.',
    'Pakaian ini memberikan tampilan yang elegan dan stylish.',
    'Ukuran pakaian sangat sesuai dengan ukuran yang tertera, tidak terlalu longgar atau ketat.',
    'Warnanya tidak luntur setelah beberapa kali dicuci.',
    'Saya sudah membeli pakaian ini beberapa bulan yang lalu dan masih terlihat seperti baru.',
    'Modelnya sangat cocok dengan bentuk tubuh dan memberikan tampilan yang lebih menarik.',
    'Pilihan warna yang beragam membuat saya ingin memiliki lebih dari satu.',
    'Pakaian ini adalah salah satu favorit saya di lemari pakaian.',
    'Sangat puas dengan kualitas pakaian dan harganya yang terjangkau.',
    'Menerima banyak pujian tentang pakaian ini saat saya mengenakannya.',
    'Bahan pakaian tidak mudah kusut, sangat praktis untuk dibawa bepergian.',
    'Saya merasa percaya diri dan cantik saat mengenakan pakaian ini.',
    'Tidak hanya nyaman, tapi juga memberikan kesan yang berkelas.',
    'Pakaian ini memberikan nilai tambah bagi penampilan saya di acara khusus.',
    'Pakaian ini memenuhi semua ekspektasi saya, dari kualitas hingga desainnya.',
    'Sangat puas dengan produk ini dan pasti akan membeli lagi dari brand ini.',
    'Pakaian ini memiliki gaya yang timeless dan tidak mudah ketinggalan mode.',
    'Saya tidak bisa berhenti mengenakan pakaian ini, sangat cocok dengan gaya saya.',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ];
}
